### ISSUE TITLE
Herokuapp respond 500

### ISSUE THREAD

**Issue by Slaals** [Falconerd/discord-bot-github#19]
Hi @Falconerd,

This project is awesome!

I tried to implement it by creating a webhook to `https://discordbotgithub.herokuapp.com` but it seems it's down.

Are you still working on it since it's a development branch?

**Comment by Falconerd** [comment]
Hey Slaals, currently I have put it on hold as I'm busy with work.

I've tried setting up a new webhook and it seems the test webhook returns a 500 because I have not coded for that type of event. I will take a look into this ASAP. In the mean time, the webhook should work with all other event payloads.

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/17460455/8cd74c08-5c67-11e6-8df4-ff2a1a6c7ef5.png)

**Comment by Falconerd** [comment]
@Bluscream There is only a POST route set up at that address.

**Comment by Tillerino** [comment]
So it _works_ but returns a 500 anyway?

**Comment by Falconerd** [comment]
@Tillerino Yeah, it will work with nearly all event types, just not the initial one which GitHub sends to test... It's something I want to fix as soon as I can as it is misleading to see a 500 error and then assume something will work.
