### ISSUE TITLE
"Repository not found." for private repo.

### ISSUE THREAD

**Issue by Uricorn** [Falconerd/discord-bot-github#38]
I added a normal repo just fine, when I tried adding a private one it said "Repository not found."

Is there anything wrong with my settings?
![capture](https://cloud.githubusercontent.com/assets/5571265/19573728/02635bb4-9710-11e6-9683-899db322bff3.png)

**Comment by Thrax989** [comment]
use the url attached to your git project example look in your hyper link 

Should say your user name 
Uricorn/ Project name not sure what your project name is 

Once your done locating that use 
!dbg add Unicorn/Whatever name is attached to your porject 

for me i used mine 

!dbg add Thrax989/Project-Phoenix

**Comment by Uricorn** [comment]
I did that, it worked for the normal repo and not the private one. Hence the issue here :)

**Comment by Thrax989** [comment]
Oh shoot sorry Im replying on my phone I must of miss read over your message sorry about that !

I have not attempted a private ill try in a bit and give feed back .

**Comment by Falconerd** [comment]
Hey, I must have missed this in my testing. I already had subscriptions to private repositories from the previous version, so I didn't realise that adding them wasn't working. It seems I had the idea to implement a token system for private repositories, according to this line https://github.com/Falconerd/discord-bot-github/blob/develop-es6/src/commands.js#L21. I will make sure to put this at the top of the list for updates, otherwise feel free to make a PR if you have time.

**Comment by AlexAndHisScripts** [comment]
It is still not working.

**Comment by hexcowboy** [comment]
I'm still having issues adding a private repository

```
GitHub
BOT
 — Today at 9:46 AM
Repository not found.
```
